small tweaks

diff --git a/sblive2iso b/sblive2iso
--- a/sblive2iso
+++ b/sblive2iso
@@ -14,6 +14,16 @@
 PROGNAME=${0##*/}
 VERSION="0.1"
 
+# trap and print errors 
+set -e -o pipefail
+function print_error {
+    read line file <<<$(caller)
+    echo "An error occurred in line $line of file $file:" >&2
+    sed "${line}q;d" "$file" >&2
+}
+trap print_error ERR
+
+
 clean_up() { # Perform pre-exit housekeeping
   return
 }
@@ -135,6 +145,7 @@ if [[ $REPLY =~ ^[Yy]$ ]]; then
     if [ -d "$TEMP_DIR" ]; then rm -R $TEMP_DIR; fi
 
   mkdir -p "$TEMP_DIR"
+  
   echo -e "${GRN} ###### Extracting $file_name ${NC} tar into  $TEMP_DIR ######"
   tar -xf "$path" -C "$TEMP_DIR"
 
@@ -170,6 +181,8 @@ if [[ $REPLY =~ ^[Yy]$ ]]; then
   $TEMP_DIR
 fi
 echo ""
+
+rm -R $TEMP_DIR
 
 graceful_exit
 
diff --git a/set-boot2iso b/set-boot2iso
--- a/set-boot2iso
+++ b/set-boot2iso
@@ -1,6 +1,7 @@
 #!/bin/bash
 # ---------------------------------------------------------------------------
 # set-boot2iso - Set up this machine to boot from iso 
+#              - modifies the grub boot configuration
 
 # Copyright 2020, Rov,,, <rov@rov-kvm>
 # All rights reserved.
@@ -13,6 +14,15 @@
 
 PROGNAME=${0##*/}
 VERSION="0.1"
+
+# trap and print errors 
+set -e -o pipefail
+function print_error {
+    read line file <<<$(caller)
+    echo "An error occurred in line $line of file $file:" >&2
+    sed "${line}q;d" "$file" >&2
+}
+trap print_error ERR
 
 clean_up() { # Perform pre-exit housekeeping
   return
